name: Build Image And Push To Registry

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    name: Build the docker image and push to registry
    runs-on: [ ubuntu-latest ]

    steps:
    - 
        name: Extract git tag
        run: echo "GIT_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
    -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
            push: true
            tags: ares30841167/ncu-human-sys-auto-sign:${{ env.GIT_TAG }}